### ISSUE TITLE
Update FTP fails

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#221]
When trying to add an extra FTP from a specific data

Run # Make sure database and migration directories exist

In MissingConfigurationFile.php line [14](https://github.com/pdoteter/Strava-activity/actions/runs/7321257717/job/19941414752#step:6:15):
                                                         
  It was not possible to locate any configuration file.  
                                                         

migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--db-configuration DB-CONFIGURATION] [--] [<version>]

Error: Process completed with exit code 1.

**Comment by robiningelbrecht** [comment]
@pdoteter ok, kinda sorta a nasty bug. I forgot to update the update-ftp workflow while refactoring into separate databases.
The problem is that by default, a github workflow is not allowed to push an updated github workflow. This means that my "update template" workflow cannot update and push a new version of "update-ftp" workflow.

I will add a comment in the readme how you can fix this (spoiler, you will have to manually copy the new workflow files to your repo and push then, via GitHub UI or via termonal)

**Comment by robiningelbrecht** [comment]
@pdoteter You'll have to update these 2 files in your repository. After doing so, updating FTP should work again:
* https://github.com/robiningelbrecht/strava-activities-template/blob/master/.github/workflows/update-ftp.yml
* https://github.com/robiningelbrecht/strava-activities-template/blob/master/.github/workflows/update-key-value-store.yml
